import type { Metadata } from "next";
import { Geist, Geist_Mono, Pacifico } from "next/font/google";
import "./globals.css";

// Configure GeistSans with explicit weight and display
const geistSans = Geist({
  weight: ["400", "700"], // Specify weights as needed
  subsets: ["latin"],
  display: "swap",
  variable: "--font-geist-sans",
});

// Configure GeistMono with explicit weight and display
const geistMono = Geist_Mono({
  weight: ["400", "700"], // Specify weights as needed
  subsets: ["latin"],
  display: "swap",
  variable: "--font-geist-mono",
});

// Configure Pacifico (unchanged)
const pacifico = Pacifico({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
  variable: "--font-pacifico",
});

export const metadata: Metadata = {
  title: "ProxyBot",
  description: "Generated by DK (R)",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${pacifico.variable} antialiased`}
        suppressHydrationWarning // Temporary workaround for __processed_ attribute
      >
        {children}
      </body>
    </html>
  );
}